<a href="https://colab.research.google.com/github/vaibhavlokunde/AI-ML/blob/main/CreditCardFraudModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import sklearn
from torch import nn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
file_path='/content/creditcard.csv'
credit_data=pd.read_csv(file_path).dropna()

In [10]:
credit_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [11]:
credit_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [12]:
credit_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [13]:
credit_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [15]:
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [62]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(credit_data.drop(columns=["Class"]))  # Drop target column
y = credit_data["Class"].values

In [63]:
#Train and test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42)

len(X_train), len(X_test), len(y_train), len(y_test)

(227845, 56962, 227845, 56962)

In [64]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(sampling_strategy=0.2)  # Increase fraud cases to 20% of total
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [65]:
X_train_tensor = torch.tensor(X_train_resampled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_resampled, dtype=torch.float32).unsqueeze(1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).unsqueeze(1)

In [66]:
class CreditCardModel(nn.Module):
    def __init__(self, n_input=30, n_hidden=32, n_output=1):
        super().__init__()
        self.fc1 = nn.Linear(n_input, n_hidden)
        self.bn1 = nn.BatchNorm1d(n_hidden)
        self.fc2 = nn.Linear(n_hidden, n_hidden)
        self.bn2 = nn.BatchNorm1d(n_hidden)
        self.fc3 = nn.Linear(n_hidden, n_output)
        self.dropout = nn.Dropout(0.3)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.fc1(x)
        x = self.bn1(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc2(x)
        x = self.bn2(x)
        x = self.relu(x)
        x = self.dropout(x)
        x = self.fc3(x)
        return x

In [67]:
model_1=CreditCardModel(n_input=X_train.shape[1],n_hidden=64,n_output=1)
model_1

CreditCardModel(
  (fc1): Linear(in_features=30, out_features=64, bias=True)
  (bn1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc2): Linear(in_features=64, out_features=64, bias=True)
  (bn2): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (fc3): Linear(in_features=64, out_features=1, bias=True)
  (dropout): Dropout(p=0.3, inplace=False)
  (relu): ReLU()
)

In [68]:
fraud_weight = (y_train_resampled == 0).sum() / (y_train_resampled == 1).sum()
loss_fn = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([fraud_weight]))
optimizer=torch.optim.Adam(model_1.parameters(),lr=0.001)

In [69]:
print(torch.isnan(torch.tensor(X_train)).any(), torch.isnan(torch.tensor(y_train)).any())  # Should print False

tensor(False) tensor(False)

In [70]:
def accuracy_fn(y_true,y_pred):
  correct=torch.eq(y_true,y_pred).sum().item()
  acc=correct/len(y_pred)
  return acc

In [75]:
epochs = 100
for epoch in range(epochs):
    model_1.train()
    optimizer.zero_grad()

    # Forward Pass
    y_logits = model_1(X_train_tensor)
    y_pred_probs = torch.sigmoid(y_logits)  # Convert logits to probabilities
    y_pred = (y_pred_probs > 0.3).float()  # Lower threshold to detect more fraud cases

    # Compute Loss
    loss = loss_fn(y_logits, y_train_tensor)

    # Compute Accuracy
    acc = (y_pred == y_train_tensor).float().mean() * 100

    # Backpropagation
    loss.backward()
    optimizer.step()

    # Evaluation
    model_1.eval()
    with torch.no_grad():
        test_logits = model_1(X_test_tensor)
        test_pred_probs = torch.sigmoid(test_logits)
        test_pred = (test_pred_probs > 0.3).float()
        test_loss = loss_fn(test_logits, y_test_tensor)
        test_acc = (test_pred == y_test_tensor).float().mean() * 100

    # Print every 10 epochs
    if epoch % 10 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}, Acc: {acc:.2f}% | Test Loss: {test_loss:.5f}, Test Acc: {test_acc:.2f}%")

Epoch: 0 | Loss: 1.25675, Acc: 15.73% | Test Loss: 0.66978, Test Acc: 0.23%
Epoch: 10 | Loss: 0.75051, Acc: 17.90% | Test Loss: 0.63186, Test Acc: 0.25%
Epoch: 20 | Loss: 0.60236, Acc: 23.89% | Test Loss: 0.51352, Test Acc: 0.81%
Epoch: 30 | Loss: 0.51664, Acc: 41.73% | Test Loss: 0.41440, Test Acc: 27.30%
Epoch: 40 | Loss: 0.45079, Acc: 61.76% | Test Loss: 0.34665, Test Acc: 69.48%
Epoch: 50 | Loss: 0.39942, Acc: 73.74% | Test Loss: 0.29986, Test Acc: 82.07%
Epoch: 60 | Loss: 0.35910, Acc: 80.21% | Test Loss: 0.26672, Test Acc: 85.91%
Epoch: 70 | Loss: 0.32692, Acc: 84.44% | Test Loss: 0.24044, Test Acc: 87.91%
Epoch: 80 | Loss: 0.29959, Acc: 87.29% | Test Loss: 0.21830, Test Acc: 89.49%
Epoch: 90 | Loss: 0.27755, Acc: 89.27% | Test Loss: 0.19991, Test Acc: 90.77%

In [79]:
torch.manual_seed(42)
with torch.inference_mode():
    y_logits = model_1(X_test_tensor)
    y_pred_probs = torch.sigmoid(y_logits)
    y_preds = (y_pred_probs > 0.3).float()

y_preds[:10].reshape(1,10), y_test[:10]

(tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0]))